### ISSUE TITLE
Load CTA Bus Ridership Data

### ISSUE THREAD

**Issue by vingkan** [scarletstudio/transithealth#18]
The CTA bus ridership dataset on the Chicago Data Portal has ~0.8M records, each representing one day and one route.

- Data Portal: [CTA Bus Ridership - Bus Routes - Daily Totals By Route](https://data.cityofchicago.org/Transportation/CTA-Ridership-Bus-Routes-Daily-Totals-by-Route/jyb9-n7fm)
- Each record contains a date for time-based metrics
- Community area is not included, but we might be able to use [geographic data about the bus route stops](https://data.cityofchicago.org/Transportation/CTA-Bus-Stops/hvnx-qtky) to create community-based metrics, however this would be a stretch project and is not required for loading the data

Read the documentation on how to add a new dataset:

- [Short Guide](https://github.com/scarletstudio/transithealth/blob/main/docs/pages/tasks.md#extract-a-dataset)
- [Full Guide](https://github.com/scarletstudio/transithealth/blob/main/docs/pages/new_dataset.md)

This task will involve at least three pull requests:

- [x] Extract dataset
- [x] Transform dataset
- [x] Load dataset

Once loaded, we can start developing metrics and questions based on this data.

**Comment by dragontunglam** [comment]
I have added script to extract data set for this issue. Can you please review for me? Thank you.

**Comment by vingkan** [comment]
Camilo finished this in #89
